CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(64) PRIMARY KEY,
    description VARCHAR(255),
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checksum VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS providers (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    provider_type VARCHAR(64),
    base_url VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    format_endpoints JSON DEFAULT ('[]'),
    models JSON DEFAULT ('[]'),
    supported_formats JSON DEFAULT ('[]'),
    endpoints JSON DEFAULT ('{}'),
    rate_limit_config JSON,
    timeout_config JSON,
    retry_config JSON,
    metadata JSON,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tokens (
    id VARCHAR(64) PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    name VARCHAR(255),
    token_value TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    quota_total BIGINT,
    quota_used BIGINT DEFAULT 0,
    quota_remaining BIGINT,
    quota_reset_at TIMESTAMP,
    rate_limited BOOLEAN DEFAULT FALSE,
    rate_limit_reset_at TIMESTAMP,
    failure_count INT DEFAULT 0,
    consecutive_failures INT DEFAULT 0,
    last_failure_at TIMESTAMP,
    last_success_at TIMESTAMP,
    last_used_at TIMESTAMP,
    total_requests BIGINT DEFAULT 0,
    success_requests BIGINT DEFAULT 0,
    success_rate DECIMAL(5,2),
    version INT NOT NULL DEFAULT 0,
    metadata JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
    INDEX idx_provider_status (provider_id, status),
    INDEX idx_status (status),
    INDEX idx_last_used (last_used_at),
    INDEX idx_rate_limit_reset (rate_limit_reset_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS models (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    description TEXT,
    model_type VARCHAR(64),
    context_window INT,
    max_output_tokens INT,
    input_price_per_1k DECIMAL(10, 6),
    output_price_per_1k DECIMAL(10, 6),
    enabled BOOLEAN DEFAULT TRUE,
    version INT NOT NULL DEFAULT 0,
    metadata JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS model_provider_bindings (
    id VARCHAR(64) PRIMARY KEY,
    model_id VARCHAR(64) NOT NULL,
    provider_id VARCHAR(64) NOT NULL,
    upstream_model_name VARCHAR(255) DEFAULT '',
    weight INT DEFAULT 1,
    priority INT DEFAULT 0,
    enabled BOOLEAN DEFAULT TRUE,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE,
    FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
    UNIQUE KEY uk_model_provider (model_id, provider_id),
    INDEX idx_model (model_id),
    INDEX idx_provider (provider_id),
    INDEX idx_enabled (enabled),
    INDEX idx_model_enabled (model_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS groups (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    load_balance_strategy VARCHAR(64) NOT NULL DEFAULT 'round_robin',
    rate_limit_config JSON,
    quota_config JSON,
    enabled BOOLEAN DEFAULT TRUE,
    version INT NOT NULL DEFAULT 0,
    metadata JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS request_logs (
    id VARCHAR(64) PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    timestamp TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    client_ip VARCHAR(64),
    user_agent TEXT,
    api_key_id VARCHAR(64),
    api_key_name VARCHAR(255),
    group_id VARCHAR(64),
    route VARCHAR(128),
    model_id VARCHAR(64),
    model_name VARCHAR(255),
    provider_id VARCHAR(64),
    provider_name VARCHAR(255),
    token_id VARCHAR(64),
    upstream_model_name VARCHAR(255),
    interface_type VARCHAR(32),
    source_format VARCHAR(32),
    target_format VARCHAR(32),
    protocol_converted BOOLEAN DEFAULT FALSE,
    is_streaming BOOLEAN DEFAULT FALSE,
    request_body_size INT,
    max_tokens INT,
    request_headers TEXT,
    request_body TEXT,
    response_headers TEXT,
    response_body TEXT,
    input_tokens INT DEFAULT 0,
    output_tokens INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    cache_hit BOOLEAN DEFAULT FALSE,
    cache_type VARCHAR(16),
    cache_key VARCHAR(64),
    cache_read_input_tokens INT DEFAULT 0,
    cache_saved_tokens INT DEFAULT 0,
    first_byte_latency_ms INT,
    total_latency_ms INT,
    provider_latency_ms INT,
    status_code INT,
    success BOOLEAN DEFAULT FALSE,
    error_code VARCHAR(64),
    error_message TEXT,
    retry_count INT DEFAULT 0,
    fallback_used BOOLEAN DEFAULT FALSE,
    estimated_cost DECIMAL(10, 6),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp (timestamp),
    INDEX idx_api_key_time (api_key_id, timestamp),
    INDEX idx_provider_model (provider_id, model_id, timestamp),
    INDEX idx_success (success),
    INDEX idx_interface_type (interface_type),
    INDEX idx_cache_hit (cache_hit),
    INDEX idx_api_key_name (api_key_name, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS api_keys (
    id VARCHAR(64) PRIMARY KEY,
    key_hash VARCHAR(128) NOT NULL UNIQUE,
    key_prefix VARCHAR(16) NOT NULL,
    plain_key VARCHAR(128) DEFAULT NULL,
    name VARCHAR(255),
    group_id VARCHAR(64),
    rate_limit_config JSON,
    quota_config JSON,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    metadata JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL,
    INDEX idx_key_hash (key_hash),
    INDEX idx_status (status),
    INDEX idx_group (group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS provider_health_checks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    token_id VARCHAR(64),
    status VARCHAR(20) NOT NULL,
    latency_ms INT,
    error_rate DECIMAL(5,2),
    error_message TEXT,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
    INDEX idx_provider_time (provider_id, checked_at),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS circuit_breaker_states (
    provider_id VARCHAR(64) PRIMARY KEY,
    state VARCHAR(20) NOT NULL,
    failure_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    last_failure_at TIMESTAMP,
    last_success_at TIMESTAMP,
    next_retry_at TIMESTAMP,
    half_open_requests INT DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE CASCADE,
    INDEX idx_state (state),
    INDEX idx_next_retry (next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reconciliation_records (
    id VARCHAR(64) PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    before_state JSON,
    after_state JSON,
    difference JSON,
    corrected_at TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_type (type),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    admin_token_prefix VARCHAR(16),
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(64) NOT NULL,
    changes JSON,
    ip_address VARCHAR(64),
    user_agent TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_resource (resource_type, resource_id),
    INDEX idx_action (action),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
